### PR TITLE
Changed Schema (a lot), Refactored models using mixins, installed pagedown for markdown support

### PR DESCRIPTION
**Pull request by natsn**

### CODE REVIEW

**Comment by natsn** [comment]
Loads of typos in here. My apologies will update shortly

**Comment by natsn** [comment]
Ok, now we should be good to go :P

**Comment by natsn** [comment]
I hear angular is big on markdown. Plus HTML is not very safe... <script>

**Comment by natsn** [comment]
Does anyone know a good DBA or schema designer who could review this? https://raw.githubusercontent.com/natsn/wibi/master/project/erd.png

**Comment by TrentDeLisle** [comment]
Well level, section and curriculum could be consolidated into the page
table. The stars table could be consolidated into the profile. Unread
messages counter could be added to the profile and could be incremented up
and set back to zero upon the view. We could create three different types
of user profiles so that way there isn't a comparison it would be
trainer/coach and participant and they would all have their own user
profiles the coach welcome video could go inside the coach profile and any
other little tweaks could be set into the profiles. Tips could also be
related to pages.

**Comment by natsn** [comment]
@TrentDeLisle That would be a very normalized approach. Some of what you are describing would work, other parts would not. For instance, with a Page object simply having a field describing the level instead of referencing a separate level object the relationships could not be established, grouping would be very challenging, etc.

**Comment by natsn** [comment]
Just installed pagedown, adds a nice markdown editor to the admin. Also, updated admin.py to include ModelAdmin's. We may not need all of these. I used admin_generate management command from django_extensions (so cool)

**Comment by TrentDeLisle** [comment]
Couldn't you just sort by curriculum then by level and section... I guess
either way would rely on the backend so it wouldn't really be an
improvement cuz it would have to sit there and sort the queries anyways. It
would be Denormalizing though because it would be grouping the data instead
of grabbing multiple tables with tons of populated data. It would grab one
giant table and then work on sorting.

**Comment by TrentDeLisle** [comment]
If it was consolidated in that sense you could add a field called
curriculum ID to the participant profile that directed them to a certain
curriculum that would dictate their course of the program based on that
match. I'm just throwing out ideas.

**Comment by TrentDeLisle** [comment]
I wonder what the CPU usage of grabbing queries and sorting queries because
that's pretty much what it boils down to. I tend to think that making
multiple requests is more heavy on the servers but I may be wrong.

**Comment by TrentDeLisle** [comment]
After doing some reading I'd say its safe to say grabbing small chunks of
data will be more beneficial to optimization. Because by the time it goes
to filter the page table it will know specifically which data it wants and
will ignore other fields. It appears that mysql relies on sorting first and
as we tell it what to grab it will specifically focus on that one field and
what we want it to grab. Which makes sense why would we want to fetch a
huge chunk of data to process when we can narrow it down in steps.

**Comment by TrentDeLisle** [comment]
What I'm saying is subjective to the context of the program, though it
really depends on the size of tables. Which in our case the page table
would be fairly large and would we wanna grab that whole table and sort it?
or would we wanna do sorting by level and section and curriculum
beforehand? Which in our case we wouldn't wanna grab that large table
because we wouldn't want to grab hundred of rows, we'd rather grab exactly
what we need. The only real way to test this properly would be to do
benchmark testing. This is also subjective to the kind of database were
working with and how they function.

**Comment by TrentDeLisle** [comment]
It's also important to note that you can apply a filter or self related
query in django so it performs a smaller request. It would be very
interesting to learn how django and databases work internally together. I
really don't understand it clearly obviously.

**Comment by natsn** [comment]
I've removed the Edge table in favor of a simple linked list. Using self referencing `nxt` and `prv` foreign keys in the Page table. Also renamed some Response table field names for clarity.

**Comment by natsn** [comment]
MERGED. Tah-Dah. Look mom, no review!

**Pull request merged**
